server:
  port: 8003
spring:
  application:
    name: nacos-getaway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: properties
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: neo_route
#          uri: lb://nacos-service
#          predicates:
#            - Path=/test

        - id: nacosSwagger
          uri: lb://nacos-service
#          uri: localhost:8002
          predicates:
            - Path=/test/*
      discovery:
        locator:
          enabled: true




#imooc:
#  service:
#    imooc-product: product
#    imooc-order: order